### ISSUE TITLE
Does not open on mojave...

### ISSUE THREAD

**Issue by theMackabu** [jaywcjlove/amac#1]
I have a screenshot
![screen shot 2019-01-05 at 3 37 18 pm](https://user-images.githubusercontent.com/32078755/50730338-ec611100-10ff-11e9-8f3e-08fdb6f62db1.png)

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/50733923-2d752600-11d1-11e9-9547-23ae0a9980b7.png)

![image](https://user-images.githubusercontent.com/1680273/50733926-3b2aab80-11d1-11e9-9ad8-3f6fbc23545c.png)
@sajjaadf

**Comment by theMackabu** [comment]
My Mac does not have that option

**Comment by theMackabu** [comment]
![screen shot 2019-01-07 at 6 46 46 pm](https://user-images.githubusercontent.com/32078755/50806702-9a112300-12ac-11e9-8270-2f068a72abb6.png)
Instead I wrote a code for it... want to see it?

**Comment by jaywcjlove** [comment]
Open `terminal`, and put in:  

```bash
sudo spctl --master-disable
```

This will give the old "anywhere"-option, when you open `settings` -> `security` 

![image](https://user-images.githubusercontent.com/1680273/50806940-bb692200-1333-11e9-91fd-9181287cc07b.png)

**Comment by theMackabu** [comment]
nice

**Comment by theMackabu** [comment]
But I still wrote a code though

**Comment by theMackabu** [comment]
I will upload now

**Comment by theMackabu** [comment]
[aMac.dmg.zip](https://github.com/jaywcjlove/amac/files/2735060/aMac.dmg.zip)
`aMac`
**Done!**
This will allow it to be ran without risking the _(everywhere)_ thing.

**Comment by theMackabu** [comment]
can you update it?

**Comment by theMackabu** [comment]
the releases?

**Comment by jaywcjlove** [comment]
I will update it when I have time. There are still many features that have not yet been completed.

You can also participate

@sajjaadf

**Comment by theMackabu** [comment]
okay
