### ISSUE TITLE
无法打开amac的应用

### ISSUE THREAD

**Issue by teefing** [jaywcjlove/amac#4]
mac上打开amac时显示 `无法打开“amac.app”，因为无法确认开发者的身份。`

**Comment by jaywcjlove** [comment]
@fantasticfbaby 你需要设置一下
![image](https://user-images.githubusercontent.com/1680273/58419226-985dc580-80bc-11e9-8be5-d9d8aa09aea5.png)

**Comment by jaywcjlove** [comment]
#5 这里有解决方法
