### ISSUE TITLE
"amac" is damaged and ca't be opened

### ISSUE THREAD

**Issue by gabbanaesteban** [jaywcjlove/amac#5]
When I try to open it, it says is damaged and recommends me to move it to trash.
<img width="416" alt="Screen Shot 2019-05-28 at 11 02 40 AM" src="https://user-images.githubusercontent.com/11374198/58489066-828de600-8138-11e9-9361-5cf99889f8d6.png">

Macbook:
<img width="581" alt="Screen Shot 2019-05-28 at 11 07 31 AM" src="https://user-images.githubusercontent.com/11374198/58489294-f7612000-8138-11e9-9280-00a83ccff2df.png">

**Comment by jaywcjlove** [comment]
@gabbanaesteban 
Solution: https://www.macbed.com/macos-high-sierra-gatekeeper/

![image](https://user-images.githubusercontent.com/1680273/58490924-99682300-81a0-11e9-9557-6bbb4933e127.png)

**Comment by cristianciofu** [comment]
I'm having the same issue as @gabbanaesteban 

The solution offered by you, @jaywcjlove is no longer available apparently... I'm also on 10.14.4

<img width="774" alt="Capture d’écran 2019-05-29 à 09 07 57" src="https://user-images.githubusercontent.com/2684268/58536611-600bd380-81f1-11e9-84fa-5f9ef2834272.png">

**Comment by cristianciofu** [comment]
Ok, I managed to fix the error by launching in the console : 

```bash
xattr -cr /Applications/amac.app
```  

It's working now :+1:

>I found the solution [in this article](http://osxdaily.com/2019/02/13/fix-app-damaged-cant-be-opened-trash-error-mac/)

**Comment by jaywcjlove** [comment]
@cristianciofu 👍
